[project]
name = "bookmemory-api"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi==0.115.8",
  "uvicorn[standard]==0.30.6",
  "pydantic==2.10.6",
  "pydantic-settings==2.7.1",
  "SQLAlchemy==2.0.37",
  "asyncpg==0.30.0",
  "alembic==1.14.1"
]
